### ISSUE TITLE
Response time

### ISSUE THREAD

**Issue by EddiesTech** [ricardonunesdev/domain-ping#2]
Hi there,
Love this package so far! Would love if you could add response time in ms. Would be very helpful seen as this is part of the definition of ping :)

Eddie

**Comment by ricardonunesdev** [comment]
Hi,

Thank you for the request.

I've added ping time in ms to the result:
```javascript
{ domain: 'github.com',
  ip: '192.30.253.112',
  ping: true,
  ping_time: 53.480,
  online: true,
  statusCode: 200,
  success: true }
```

Update the dependency in your project to the latest version:
`npm install domain-ping@latest`

Or check the latest release for the update:
 - [NPM Package](https://www.npmjs.com/package/domain-ping)
 - [Github Release](https://github.com/ricardonunesdev/domain-ping/releases/tag/v0.2.1)

If you find any problem with this update, please let me know.
Until then I'm closing this issue.

Best regards,
Ricardo
