### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by av3games** [ricardonunesdev/domain-ping#3]
How do i get just the ping time?

**Comment by ricardonunesdev** [comment]
Hi @av3games,

I'm sorry it took so long to answer this, I haven't received the notification for this issue.

You can use the `ping_time` property of the returned object.

Example:
```javascript
const domainPing = require("domain-ping");

domainPing('github.com') // Insert the domain you want to ping
    .then((res) => {
        console.log(res.ping_time); // <--- This should print the ping time (in ms)
    })
    .catch((error) => {
        console.error(error);
    });
```

Hope it helps.

Ricardo
