### ISSUE TITLE
can i get a status code in error object as well

### ISSUE THREAD

**Issue by aatif-shaikh** [ricardonunesdev/domain-ping#4]
need to get a statusCode in error object as well.

**Comment by ricardonunesdev** [comment]
Hi @aatif-shaikh,

If the domain and web server are online and reachable, there should be a valid response with the HTTP status code.

The HTTP request is the last process being run in the script, so `statusCode` is the last property being added to the response object, after all other processes have completed.

Meaning that if there's an error, it'll most likely happen before or during the HTTP request, and there is no status code at that point.

Only a valid HTTP request can return a status code: 200, 40x, 50x, etc

So I think that adding the status code to the error object is impossible, unless it's a fake one.

In what situation would you need a status code in the error object?

Ricardo
